# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://olumayowa.dev/"
title = "Olúmáyòwá.dev"
theme = "congo"

defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[languages]
[languages.en]
languageName = "English"
weight = 1

[params]
colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

[params.author]
name = "Olúmáyòwá Akinkuehinmi"
image = "img/author.jpg"
headline = "DevOps • Submarine Cable Networks • DevNet • CyberSecurity"
bio = "DevOps • Submarine Cable Networks • DevNet • CyberSecurity"
links = [
  { name = "email", url = "mailto:olumayowa@olumayowa.dev" },
  { name = "github", url = "https://github.com/akintunero" },
  { name = "linkedin", url = "https://linkedin.com/in/olumayowaa" },
  { name = "telegram", url = "https://t.me/akintunero" },
  { name = "spotify", url = "https://open.spotify.com/user/your_profile" },
  { name = "twitter", url = "https://x.com/akintunero" }
]

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]
[[menu.main]]
name = "Blog"
pageRef = "posts"
weight = 10
[[menu.main]]
name = "About"
pageRef = "about"
weight = 20

[markup.highlight]
noClasses = false
