languageCode = "en"
languageName = "English"
weight = 1

title = "Olúmáyòwá.dev"

[params]
rtl = false
isoCode = "en"
displayName = "EN"
dateFormat = "January 2, 2006"
description = "Olúmáyòwá Akinkuehinmi"

[params.author]
bio = "DevOps • Submarine Cable Networks • DevNet • CyberSecurity"
name = "Olúmáyòwá Akinkuehinmi"
image = "img/author.jpg"
headline = "DevOps • Submarine Cable Networks • DevNet • CyberSecurity"
links = [
    { name = "email", url = "mailto:olumayowa@olumayowa.dev" },
    { name = "github", url = "https://github.com/akintunero" },
    { name = "linkedin", url = "https://linkedin.com/in/olumayowaa" },
    { name = "telegram", url = "https://t.me/akintunero" },
    { name = "spotify", url = "https://open.spotify.com/user/your_profile" },
    { name = "twitter", url = "https://x.com/akintunero" }
]