# -- Main Menu --
[[main]]
name = "about"
pageRef = "about"
weight = 20

[[main]]
name = "talks"
pageRef = "talks"
weight = 30

[[main]]
name = "resume"
url = "https://drive.google.com/file/d/1a2t3iNwcWYq8J6IwMKH1o1MaxOBtqlyT/view?usp=sharing"
weight = 40
[main.params]
target = "_blank"

[[main]]
name = "podcast"
url = "https://podcasters.spotify.com/pod/show/"
weight = 50
[main.params]
target = "_blank"

[[main]]
name = "projects"
url = "https://github.com/akintunero/"
weight = 60
[main.params]
target = "_blank"

