# Main menu
[[main]]
name = "About"
pageRef = "/about/"
weight = 20

[[main]]
name = "Talks"
pageRef = "/talks/"
weight = 30

[[main]]
name = "Resume"
url = "https://drive.google.com/file/d/1psWHY2CDFMBCieaWdrkZTq3lOFbX4rxj/view?usp=sharing"
weight = 40
params = { target = "_blank" }

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 50

[[main]]
name = "Projects"
url = "https://github.com/akintunero/"
weight = 60
params = { target = "_blank" }

[[main]]
name = "Press Features"
pageRef = "/press/"
weight = 70