# -- Main Menu --
[[menu.main]]
name = "about"
pageRef = "/about/"
weight = 20

[[menu.main]]
name = "talks"
pageRef = "/talks/"
weight = 30

[[menu.main]]
name = "resume"
url = "https://drive.google.com/file/d/1a2t3iNwcWYq8J6IwMKH1o1MaxOBtqlyT/view?usp=sharing"
weight = 40
[menu.main.params]
target = "_blank"

[[menu.main]]
name = "podcast"
url = "https://podcasters.spotify.com/pod/show/"
weight = 50
[menu.main.params]
target = "_blank"

[[menu.main]]
name = "blog"
pageRef = "/blog/"
weight = 60

[[menu.main]]
name = "projects"
url = "https://github.com/akintunero/"
weight = 70
[menu.main.params]
target = "_blank"

[[menu.main]]
name = "Press Features"
pageRef = "/press/"
weight = 80
