# Main menu
[[main]]
name = "About"
pageRef = "/about/"
weight = 20

[[main]]
name = "Talks"
pageRef = "/talks/"
weight = 30

[[main]]
name = "Resume"
url = "https://drive.google.com/file/d/1a2t3iNwcWYq8J6IwMKH1o1MaxOBtqlyT/view?usp=sharing"
weight = 40
params = { target = "_blank" }

[[main]]
name = "Podcast"
url = "https://podcasters.spotify.com/pod/show/"
weight = 50
params = { target = "_blank" }

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 60

[[main]]
name = "Projects"
url = "https://github.com/akintunero/"
weight = 70
params = { target = "_blank" }

[[main]]
name = "Press Features"
pageRef = "/press/"
weight = 80