# -- Main Menu --
[[main]]
name = "about"
pageRef = "about"
weight = 20

[[main]]
name = "blog"
pageRef = "blog"
weight = 30

[[main]]
name = "talks"
pageRef = "talks"
weight = 40

[[main]]
name = "podcast"
url = "https://podcasters.spotify.com/pod/show/"
weight = 50
[main.params]
target = "_blank"

[[main]]
name = "projects"
url = "https://github.com/akintunero/"
weight = 60
[main.params]
target = "_blank"

